# Generated by Django 2.2.2 on 2020-08-13 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fileupload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classno', models.IntegerField()),
                ('file', models.FileField(upload_to='file/')),
            ],
        ),
    ]
